DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    forename VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    username VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    role VARCHAR(100) NOT NULL
);